name: retrolite_example
description: Demonstrates how to use the [Retrolite](https://pub.dev/retrolite) package.
homepage: https://github.com/flutuate/retrolite/tree/master/example
author: Luciano Bonifacio Rodrigues <flutuate.io@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  collection: ^1.14.11
  flutuate_api: ^1.0.0+1
  retrolite: ^0.0.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
