name: retrolite
description: An REST client for Dart and Flutter, litening based on [Retrofit](https://square.github.io/retrofit/).
version: 0.0.1
homepage: https://www.github.com/flutuate/retrolite
author: Luciano Bonifacio Rodrigues <flutuate.io@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
