name: retrolite
description: A RESTful API client for Dart and Flutter, with a simple API syntax, without reflection.
version: 1.0.0
homepage: https://www.github.com/flutuate/retrolite
author: Luciano Bonifacio Rodrigues <flutuate.io@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  collection: ^1.14.11
  flutuate_api: ^1.0.0+2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
